### PR TITLE
Add build dirs to gitignore

### PR DESCRIPTION
**Pull request by G07cha**
Small improvement that allows to forget about deleting build directories before committing all files for example.

### CODE REVIEW

**Comment by jsilvestre** [comment]
Hello @G07cha, thank you for the PR.

Could you please remove `build/` from the .gitignore? We are aware it's a bad practice, but we use that mechanism intensively to run applications with JS instead of CS.
* One reason to run JS instead of CS within the platform is that running node applications with CS implies a memory usage overhead.
* One reason not to build during deployment (when the app is installed) is that it's also costing resources on the Cozy.

In before we find a proper alternative, we are going to keep it versioned.

Thank you,
Joseph.

**Comment by G07cha** [comment]
@jsilvestre, thanks for your detailed answer, I've updated PR.

**Comment by jsilvestre** [comment]
Thank you very much @G07cha!

**Comment by G07cha** [comment]
@jsilvestre, you are welcome!

**Pull request merged**
