### PR TITLE
Add brunch postinstallation script

### PR DESCRIPTION
**Pull request by G07cha**
Required for building client but for some reason, don't listed in description.

### CODE REVIEW

**Comment by jsilvestre** [comment]
Following my message in the other PR, we'd rather not build in production, so I think it's not a good idea to do this.
As a side note, this would not work in production since installing with option `-g` requires running the command as administrator, which is not the case in Cozy.

Anyway, thank you for the PR, it's really appreciated!

**Comment by G07cha** [comment]
@jsilvestre, what about adding "brunch" package to requirements section?

**Comment by jsilvestre** [comment]
Yeah sure that would work, but my concerns are not about how to do it, they are about doing it. See https://github.com/cozy/cozy-template-coffee/pull/18#issuecomment-154055158 for why we don't do it.

I fully agree with you that would be very nice (I even tried it in one of my app), but that's not something the platform can handle efficiently (yet).

**Comment by G07cha** [comment]
Alright, I'm closing this and if you would like to point brunch package as requirement in Readme, I'll be happy.

**Comment by jsilvestre** [comment]
You are absolutely right, it's done! At some point we'll do something based on npm commands, which use locally installed version of all the tools needed, so you only have to do `npm install` once and you're good to go. It's something we are progressively adding, I am personally already using that system in my personal project.

**Pull request closed without merging**
